python:
  exclude:
    - examples
    - a2a
    # - agents
    - apps
    - artifacts
    - auth
    - cli
    - code_executors
    - dependencies
    - errors
    - evaluation
    - events
    - features
    - flows
    - memory
    - models
    - planners
    - platform
    - plugins
    - sessions
    - telemetry
    - tools
    - utils

typescript:
  exclude:
    # - agents
    - artifacts
    - auth
    - code_executors
    - events
    - examples
    - memory
    - models
    - plugins
    - runner
    - sessions
    - telemetry
    - tools
    - utils
